# Generated by Django 4.1.5 on 2023-01-16 13:00

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.ImageField(unique=True, upload_to=post.models.post_upload),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="What is the story behind this?",
                        null=True,
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
