# Generated by Django 3.0.8 on 2020-09-07 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
