# Generated by Django 3.0.8 on 2020-10-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/media'),
        ),
    ]
