# Generated by Django 4.1.2 on 2022-10-25 06:16

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        blank=True, null=True, upload_to=blog.models.post_upload
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, default=None, help_text="Give us a story", null=True
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
